[package]
name = "ironjvm"
authors = ["HTGAzureX1212."]
version = "18.0.0"
description = "The IronJVM binary"
edition = "2021"
license = "GPL-2.0"

[dependencies]
ironjvm_driver = { path = "../ironjvm_driver" }
