[workspace]
members = [
    "ironjvm_bootcl",
    "ironjvm_cfck",
    "ironjvm_cfparser",
    "ironjvm_javautil",
    "ironjvm_libjimage",
    "ironjvm_libjvm",
    "ironjvm_specimpl",
]

[profile.release]
debug = true
