[package]
name = "ironjvm_specimpl"
authors = ["HTGAzureX1212."]
version = "18.0.0"
description = "JVM Specification implementation for IronJVM"
edition = "2021"
license = "GPL-2.0"

[dependencies]


[features]
retrieval-api = []
